<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBK7GKUY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBK7GKUY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBK7GKUY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBK7GKUY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBK7GKUY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BK7GKUY',
    'container.build_id' => 'e0a42988',
    'container.build_time' => 1631603899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBK7GKUY');
