<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Tue Sep 14 09:18:13 CEST 2021.

define('DOMJUDGE_VERSION', '7.3.3');

define('BINDIR',      '/domjudge/bin');
define('ETCDIR',      '/domjudge/etc');
define('WEBAPPDIR',   '/domjudge/webapp');
define('LIBDIR',      '/domjudge/lib');
define('SQLDIR',      '/domjudge/sql');
define('LIBVENDORDIR','/domjudge/lib/vendor');
define('LOGDIR',      '/domjudge/output/log');
define('RUNDIR',      '/domjudge/output/run');
define('TMPDIR',      '/domjudge/output/tmp');

define('BASEURL',     'http://localhost/');

define('SUBMITCLIENT_ENABLED', 'yes');
