<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Executable extends \App\Entity\Executable implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'execid', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'md5sum', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'zipfile', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'zipfile_as_string', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'languages', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'problems_compare', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'problems_run'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'execid', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'md5sum', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'zipfile', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'zipfile_as_string', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'languages', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'problems_compare', '' . "\0" . 'App\\Entity\\Executable' . "\0" . 'problems_run'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Executable $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setExecid($execid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecid', [$execid]);

        return parent::setExecid($execid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecid()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getExecid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecid', []);

        return parent::getExecid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMd5sum($md5sum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMd5sum', [$md5sum]);

        return parent::setMd5sum($md5sum);
    }

    /**
     * {@inheritDoc}
     */
    public function getMd5sum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMd5sum', []);

        return parent::getMd5sum();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipfile($zipfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipfile', [$zipfile]);

        return parent::setZipfile($zipfile);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipfile(bool $asString = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipfile', [$asString]);

        return parent::getZipfile($asString);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipFileSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipFileSize', []);

        return parent::getZipFileSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function addLanguage(\App\Entity\Language $language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLanguage', [$language]);

        return parent::addLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLanguage(\App\Entity\Language $language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLanguage', [$language]);

        return parent::removeLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', []);

        return parent::getLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function addProblemsCompare(\App\Entity\Problem $problemsCompare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProblemsCompare', [$problemsCompare]);

        return parent::addProblemsCompare($problemsCompare);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProblemsCompare(\App\Entity\Problem $problemsCompare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProblemsCompare', [$problemsCompare]);

        return parent::removeProblemsCompare($problemsCompare);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemsCompare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemsCompare', []);

        return parent::getProblemsCompare();
    }

    /**
     * {@inheritDoc}
     */
    public function addProblemsRun(\App\Entity\Problem $problemsRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProblemsRun', [$problemsRun]);

        return parent::addProblemsRun($problemsRun);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProblemsRun(\App\Entity\Problem $problemsRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProblemsRun', [$problemsRun]);

        return parent::removeProblemsRun($problemsRun);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemsRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemsRun', []);

        return parent::getProblemsRun();
    }

}
