<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Testcase extends \App\Entity\Testcase implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'testcaseid', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'md5sum_input', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'md5sum_output', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'probid', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'rank', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'description_as_string', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'orig_input_filename', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'image_type', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'sample', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'deleted', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'judging_runs', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'external_runs', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'content', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'problem'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'testcaseid', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'md5sum_input', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'md5sum_output', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'probid', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'rank', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'description_as_string', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'orig_input_filename', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'image_type', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'sample', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'deleted', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'judging_runs', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'external_runs', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'content', '' . "\0" . 'App\\Entity\\Testcase' . "\0" . 'problem'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Testcase $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTestcaseid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTestcaseid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestcaseid', []);

        return parent::getTestcaseid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMd5sumInput($md5sumInput)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMd5sumInput', [$md5sumInput]);

        return parent::setMd5sumInput($md5sumInput);
    }

    /**
     * {@inheritDoc}
     */
    public function getMd5sumInput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMd5sumInput', []);

        return parent::getMd5sumInput();
    }

    /**
     * {@inheritDoc}
     */
    public function setMd5sumOutput($md5sumOutput)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMd5sumOutput', [$md5sumOutput]);

        return parent::setMd5sumOutput($md5sumOutput);
    }

    /**
     * {@inheritDoc}
     */
    public function getMd5sumOutput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMd5sumOutput', []);

        return parent::getMd5sumOutput();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbid($probid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbid', [$probid]);

        return parent::setProbid($probid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbid', []);

        return parent::getProbid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRank($rank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRank', [$rank]);

        return parent::setRank($rank);
    }

    /**
     * {@inheritDoc}
     */
    public function getRank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRank', []);

        return parent::getRank();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(bool $asString = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', [$asString]);

        return parent::getDescription($asString);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigInputFilename($origInputFilename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigInputFilename', [$origInputFilename]);

        return parent::setOrigInputFilename($origInputFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigInputFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigInputFilename', []);

        return parent::getOrigInputFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageType($imageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageType', [$imageType]);

        return parent::setImageType($imageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageType', []);

        return parent::getImageType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSample($sample)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSample', [$sample]);

        return parent::setSample($sample);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted(bool $deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSample()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSample', []);

        return parent::getSample();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function addJudgingRun(\App\Entity\JudgingRun $judgingRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJudgingRun', [$judgingRun]);

        return parent::addJudgingRun($judgingRun);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJudgingRun(\App\Entity\JudgingRun $judgingRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJudgingRun', [$judgingRun]);

        return parent::removeJudgingRun($judgingRun);
    }

    /**
     * {@inheritDoc}
     */
    public function getJudgingRuns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudgingRuns', []);

        return parent::getJudgingRuns();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstJudgingRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstJudgingRun', []);

        return parent::getFirstJudgingRun();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstExternalRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstExternalRun', []);

        return parent::getFirstExternalRun();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent(?\App\Entity\TestcaseContent $content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent(): ?\App\Entity\TestcaseContent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblem(\App\Entity\Problem $problem = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblem', [$problem]);

        return parent::setProblem($problem);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblem', []);

        return parent::getProblem();
    }

    /**
     * {@inheritDoc}
     */
    public function addExternalRun(\App\Entity\ExternalRun $externalRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExternalRun', [$externalRun]);

        return parent::addExternalRun($externalRun);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExternalRun(\App\Entity\ExternalRun $externalRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExternalRun', [$externalRun]);

        return parent::removeExternalRun($externalRun);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalRuns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalRuns', []);

        return parent::getExternalRuns();
    }

}
