<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cTjBXfv' shared service.

return $this->privates['.service_locator.cTjBXfv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'externalJudgement' => ['privates', '.errored..service_locator.cTjBXfv.App\\Entity\\ExternalJudgement', NULL, 'Cannot autowire service ".service_locator.cTjBXfv": it references class "App\\Entity\\ExternalJudgement" but no such service exists.'],
], [
    'externalJudgement' => 'App\\Entity\\ExternalJudgement',
]);
