<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.1qpuAO7.ZipArchive' shared service.

$this->throw('Cannot autowire service ".service_locator.1qpuAO7": it references class "ZipArchive" but no such service exists.');
