<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.value.zrvvYJt' shared service.

return $this->privates['.value.zrvvYJt'] = \current([0 => \dirname(__DIR__, 4)]);
