<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RGIiAl4' shared service.

return $this->privates['.service_locator.RGIiAl4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'viewhandler' => ['services', 'fos_rest.view_handler', 'getFosRest_ViewHandlerService.php', true],
], [
    'viewhandler' => '?',
]);
