<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p8zqwCr' shared service.

return $this->privates['.service_locator.p8zqwCr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'formFactory' => ['services', 'form.factory', 'getForm_FactoryService.php', true],
], [
    'formFactory' => '?',
]);
