<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\BalloonService' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/BalloonService.php';

return $this->privates['App\\Service\\BalloonService'] = new \App\Service\BalloonService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['App\\Service\\ConfigurationService'] ?? $this->getConfigurationServiceService()));
