<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\ContestExportType' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/src/Form/Type/ContestExportType.php';

return $this->privates['App\\Form\\Type\\ContestExportType'] = new \App\Form\Type\ContestExportType();
