<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\CheckDatabaseConfigurationDefaultValuesCommand' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/CheckDatabaseConfigurationDefaultValuesCommand.php';

return $this->services['console.command.public_alias.App\\Command\\CheckDatabaseConfigurationDefaultValuesCommand'] = new \App\Command\CheckDatabaseConfigurationDefaultValuesCommand(($this->services['App\\Service\\ConfigurationService'] ?? $this->getConfigurationServiceService()));
