<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Serializer\ContestVisitor' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
include_once \dirname(__DIR__, 4).'/src/Serializer/ContestVisitor.php';

return $this->privates['App\\Serializer\\ContestVisitor'] = new \App\Serializer\ContestVisitor(($this->services['App\\Service\\ConfigurationService'] ?? $this->getConfigurationServiceService()));
