<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\DOMJudgeBasicAuthenticator' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-guard/AuthenticatorInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-guard/AbstractGuardAuthenticator.php';
include_once \dirname(__DIR__, 4).'/src/Security/DOMJudgeBasicAuthenticator.php';

return $this->privates['App\\Security\\DOMJudgeBasicAuthenticator'] = new \App\Security\DOMJudgeBasicAuthenticator(($this->services['security.csrf.token_manager'] ?? $this->load('getSecurity_Csrf_TokenManagerService.php')), ($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php')), ($this->services['security.password_encoder'] ?? $this->getSecurity_PasswordEncoderService()));
