<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\DOMJudgeXHeadersAuthenticator' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-guard/AuthenticatorInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-guard/AbstractGuardAuthenticator.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Util/TargetPathTrait.php';
include_once \dirname(__DIR__, 4).'/src/Security/DOMJudgeXHeadersAuthenticator.php';

return $this->privates['App\\Security\\DOMJudgeXHeadersAuthenticator'] = new \App\Security\DOMJudgeXHeadersAuthenticator(($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php')), ($this->services['security.password_encoder'] ?? $this->getSecurity_PasswordEncoderService()), ($this->services['App\\Service\\ConfigurationService'] ?? $this->getConfigurationServiceService()), ($this->services['router'] ?? $this->getRouterService()));
