<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer.exception_normalizer.jms' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/AbstractExceptionNormalizer.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/ExceptionHandler.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/friendsofsymfony/rest-bundle/Util/ExceptionValueMap.php';

return $this->privates['fos_rest.serializer.exception_normalizer.jms'] = new \FOS\RestBundle\Serializer\Normalizer\ExceptionHandler(new \FOS\RestBundle\Util\ExceptionValueMap(['Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException' => true, 'Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException' => true, 'Symfony\\Component\\HttpKernel\\Exception\\NotAcceptableHttpException' => true, 'Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException' => true, 'Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException' => true]), true);
