<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fragment.renderer.hinclude' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/Fragment/FragmentRendererInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/Fragment/RoutableFragmentRenderer.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/Fragment/HIncludeFragmentRenderer.php';

$this->privates['fragment.renderer.hinclude'] = $instance = new \Symfony\Component\HttpKernel\Fragment\HIncludeFragmentRenderer(($this->services['twig'] ?? $this->getTwigService()), ($this->privates['uri_signer'] ?? ($this->privates['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner($this->getEnv('APP_SECRET')))), NULL);

$instance->setFragmentPath('/_fragment');

return $instance;
