<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Jury\ImportExportController' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
include_once \dirname(__DIR__, 4).'/src/Controller/Jury/ImportExportController.php';
include_once \dirname(__DIR__, 4).'/src/Service/BaylorCmsService.php';

$a = ($this->privates['App\\Service\\DOMJudgeService'] ?? $this->getDOMJudgeServiceService());
$b = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

$this->services['App\\Controller\\Jury\\ImportExportController'] = $instance = new \App\Controller\Jury\ImportExportController(new \App\Service\BaylorCmsService($a, $b, '7.3.3'), ($this->privates['App\\Service\\ImportExportService'] ?? $this->load('getImportExportServiceService.php')), $b, ($this->privates['App\\Service\\ScoreboardService'] ?? $this->getScoreboardServiceService()), $a, ($this->services['App\\Service\\ConfigurationService'] ?? $this->getConfigurationServiceService()), ($this->privates['App\\Service\\EventLogService'] ?? $this->getEventLogServiceService()), '7.3.3');

$instance->setContainer(($this->privates['.service_locator.rsQA3TH'] ?? $this->load('get_ServiceLocator_RsQA3THService.php'))->withContext('App\\Controller\\Jury\\ImportExportController', $this));

return $instance;
