<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.WgjgUIw.App\Entity\JudgingRun' shared service.

$this->throw('Cannot autowire service ".service_locator.WgjgUIw": it references class "App\\Entity\\JudgingRun" but no such service exists.');
