<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\LoadExampleDataCommand' shared autowired service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/LoadExampleDataCommand.php';

return $this->services['console.command.public_alias.App\\Command\\LoadExampleDataCommand'] = new \App\Command\LoadExampleDataCommand();
