<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.model_describers.object' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/ModelDescriber/ModelDescriberInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareTrait.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php';

return $this->privates['nelmio_api_doc.model_describers.object'] = new \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber(($this->privates['property_info'] ?? $this->getPropertyInfoService()), ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()), new RewindableGenerator(function () {
    yield 0 => ($this->privates['nelmio_api_doc.object_model.property_describers.array'] ?? $this->load('getNelmioApiDoc_ObjectModel_PropertyDescribers_ArrayService.php'));
    yield 1 => ($this->privates['nelmio_api_doc.object_model.property_describers.boolean'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.boolean'] = new \Nelmio\ApiDocBundle\PropertyDescriber\BooleanPropertyDescriber()));
    yield 2 => ($this->privates['nelmio_api_doc.object_model.property_describers.float'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.float'] = new \Nelmio\ApiDocBundle\PropertyDescriber\FloatPropertyDescriber()));
    yield 3 => ($this->privates['nelmio_api_doc.object_model.property_describers.integer'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.integer'] = new \Nelmio\ApiDocBundle\PropertyDescriber\IntegerPropertyDescriber()));
    yield 4 => ($this->privates['nelmio_api_doc.object_model.property_describers.string'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.string'] = new \Nelmio\ApiDocBundle\PropertyDescriber\StringPropertyDescriber()));
    yield 5 => ($this->privates['nelmio_api_doc.object_model.property_describers.date_time'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.date_time'] = new \Nelmio\ApiDocBundle\PropertyDescriber\DateTimePropertyDescriber()));
    yield 6 => ($this->privates['nelmio_api_doc.object_model.property_describers.object'] ?? ($this->privates['nelmio_api_doc.object_model.property_describers.object'] = new \Nelmio\ApiDocBundle\PropertyDescriber\ObjectPropertyDescriber()));
}, 7));
