<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.describers.route.default' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/DescriberInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareTrait.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Describer/RouteDescriber.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/nelmio/api-doc-bundle/Util/ControllerReflector.php';

return $this->privates['nelmio_api_doc.describers.route.default'] = new \Nelmio\ApiDocBundle\Describer\RouteDescriber(($this->privates['nelmio_api_doc.routes.default'] ?? $this->load('getNelmioApiDoc_Routes_DefaultService.php')), ($this->privates['nelmio_api_doc.controller_reflector'] ?? ($this->privates['nelmio_api_doc.controller_reflector'] = new \Nelmio\ApiDocBundle\Util\ControllerReflector($this))), new RewindableGenerator(function () {
    yield 0 => ($this->privates['nelmio_api_doc.route_describers.fos_rest'] ?? $this->load('getNelmioApiDoc_RouteDescribers_FosRestService.php'));
    yield 1 => ($this->privates['nelmio_api_doc.route_describers.php_doc'] ?? ($this->privates['nelmio_api_doc.route_describers.php_doc'] = new \Nelmio\ApiDocBundle\RouteDescriber\PhpDocDescriber()));
    yield 2 => ($this->privates['nelmio_api_doc.route_describers.route_metadata'] ?? ($this->privates['nelmio_api_doc.route_describers.route_metadata'] = new \Nelmio\ApiDocBundle\RouteDescriber\RouteMetadataDescriber()));
}, 3));
