<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.T2eog9f.App\Entity\Problem' shared service.

$this->throw('Cannot autowire service ".service_locator.T2eog9f": it references class "App\\Entity\\Problem" but no such service exists.');
