<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'session' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-foundation/Session/SessionInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-foundation/Session/Session.php';

return $this->services['session'] = new \Symfony\Component\HttpFoundation\Session\Session(($this->privates['session.storage.native'] ?? $this->load('getSession_Storage_NativeService.php')));
