<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.listener.guard.api' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Firewall/AbstractListener.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Firewall/ListenerInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-http/Firewall/LegacyListenerTrait.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/security-guard/Firewall/GuardAuthenticationListener.php';

return $this->privates['security.authentication.listener.guard.api'] = new \Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener(($this->privates['security.authentication.guard_handler'] ?? $this->load('getSecurity_Authentication_GuardHandlerService.php')), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), 'api', new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\\Security\\DOMJudgeIPAuthenticator'] ?? $this->load('getDOMJudgeIPAuthenticatorService.php'));
    yield 1 => ($this->privates['App\\Security\\DOMJudgeBasicAuthenticator'] ?? $this->load('getDOMJudgeBasicAuthenticatorService.php'));
}, 2), ($this->privates['monolog.logger.security'] ?? $this->load('getMonolog_Logger_SecurityService.php')));
