<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.l0q8yB1.App\Entity\Team' shared service.

$this->throw('Cannot autowire service ".service_locator.l0q8yB1": it references class "App\\Entity\\Team" but no such service exists.');
