<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\UserStateUpdater' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Security/UserStateUpdater.php';

return $this->privates['App\\Security\\UserStateUpdater'] = new \App\Security\UserStateUpdater(($this->privates['App\\Service\\DOMJudgeService'] ?? $this->getDOMJudgeServiceService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
